public class Constants {
    public static final int size = 30; //rozmiar jednego pola na planszy
    public static final int columns = 50; //ilosc kolumn na planszy
    public static final int rows = 25; //ilosc rzędów na planszy
    public static final int gardenSize = 38;
    public static final int dmgDealtByFlyingPest = 10; //obrażenia zadawane przez latającego szkodnika
    public static final int dmgDealtBySpiderPest = 15; //obrażenia zadawane przez pająka
    public static final int dmgDealtByLarvaPest = 20; //obrażenia zadawane przez larwę
    public static final int fullLife = 100; //pełne życie
    public static final int noLife = 0; //brak życia
    public static final int rand10 = 10; //zakres losowania
    public static final int rand4 = 4; //zakres losowania
    public static final int roseLifeLowerLimForRep = 20; //górna granica wartosci życia dla róży przy reprodukcji
    public static final int tulipLifeUpperLimForRep = 70; //górna granica wartosci życia dla tulipana przy reprodukcji
    public static final int irisLifeLowerLimForRep = 40;
    public static final int spiderType = 2; //numer typu pająka
    public static final int spiderRepCost = 10; //koszt reprudukcji dla pająka
    public static final int larvaType = 0; //numer typu larwy
    public static final int larvaRepCost = 15; //koszt reprodukcji larwy
    public static final int flyingType = 1; //numer typu latającego szkodnika
    public static final int flyingRepCost = 20; //koszt reprodukcji latającego szkodnika
    public static final int spiderMoveCost = 20; //koszt zmiany kwiatka dla pająka
    public static final int larvaMoveCost = 10; //koszt zmiany kwiatka dla larwy
    public static final int flyingMoveCost = 25; //koszt zmiany kwiatka dla latającego szkodnika
    public static final int gardenXBeginning = 1; //początek współrzędnej x ogrodu
    public static final int gardenXEnding = columns - 11; //koniec współrzędnej x ogrodu
    public static final int gardenYBeginning = 1; //początek współrzędnej y ogrodu
    public static final int gardenYEnding = rows - 1; //koniec współrzędnej y ogrodu
    public static final int rand15 = 15; //zakres losowania
    public static final int roseType = 0; //numer typu róży
    public static final int tulipType = 1; //numer typu tulipana
    public static final int irisType = 2; //numer typu irysa
    public static final int noPestType = 3; //numer typu bez szkodnika
    public static final int roseWateringReq = 30; //ilosc życia, którą musi osiągnąć róża, żeby ją podlano
    public static final int roseWateringWorth = -50; //wartosc podlania róży (ujemna, dostosowana do metody)
    public static final int tulipWateringReq = 20; //ilosc życia, którą musi osiągnąć tulipan, żeby go podlano
    public static final int tulipWateringWorth = -40; //wartosc podlania tulipana (ujemna, dostosowana do metody)
    public static final int irisWateringReq = 25; //ilosc życia, którą musi osiągnąć irys, żeby go podlano
    public static final int irisWateringWorth = -70; //wartosc podlania irysa (ujemna, dostosowana do metody)
    public static final int spiderFullnessReq = 20; //ilosc najedzenia, jaką musi osiagnąć pająk, żeby wywołać jakis ruch
    public static final int flyingFullnessReq = 30; //ilosc najedzenia, jaką musi osiagnąć latający szkodnik, żeby wywołać jakis ruch
    public static final int larvaFullnessReq = 25; //ilosc najedzenia, jaką musi osiagnąć larwa, żeby wywołać jakis ruch
    public static final int sunWeatherLim = 10; //wyznacznik pogody słonecznej
    public static final int rainWeatherLowerLim = 11; //dolny wyznacznik pogody deszczowej
    public static final int rainWeatherUpperLim = 15; //górny wyznacznik pogody deszczowej
    public static final int droughtWeather = 16; //wyznacznik suszy
    public static final int snowWeatherOption1 = 17; //wyznacznik sniegu
    public static final int snowWeatherOption2 = 18; //wyznacznik sniegu
    public static final int hurricaneWeather = 19; //wyznacznik huraganu
    public static final int roseFeedSpider = -40; //ilosc najedzenia pająka z róży (ujemna, dostosowana do metody)
    public static final int roseFeedFlying = -50; //ilosc najedzenia latającego szkodnika z róży (ujemna, dostosowana do metody)
    public static final int roseFeedLarva = -20; //ilosc najedzenia larwy z róży (ujemna, dostosowana do metody)
    public static final int tulipFeedSpider = -40; //ilosc najedzenia pająka z tulipana (ujemna, dostosowana do metody)
    public static final int tulipFeedFlying = -30; //ilosc najedzenia latającego szkodnika z tulipana (ujemna, dostosowana do metody)
    public static final int tulipFeedLarva = -35; //ilosc najedzenia larwy z tulipana (ujemna, dostosowana do metody)
    public static final int irisFeedSpider = -45; //ilosc najedzenia pająka z irysa (ujemna, dostosowana do metody)
    public static final int irisFeedFlying = -60; //ilosc najedzenia latającego szkodnika z irysa (ujemna, dostosowana do metody)
    public static final int irisFeedLarva = -55; //ilosc najedzenia larwy z irysa (ujemna, dostosowana do metody)
    public static final int rand20 = 20; //zakres losowania
    public static final int rainLifeWorth = 80; //ilosc życia warunkująca zdażenia podczas deszczu
    public static final int droughtLifeWorth = 60; //ilosc życia warunkująca zdażenia podczas suszy
    public static final int snowLifeWorthForRose = 30; //ilosc życia warunkująca zdażenia podczas sniegu dla róży
    public static final int snowLifeWorthForTulip = 50; //ilosc życia warunkująca zdażenia podczas sniegu dla tulipana
    public static final int snowLifeWorthForIris = 70; //ilosc życia warunkująca zdażenia podczas sniegu dla irysa
    public static final int hurricaneLifeWorthForRose = 40; //ilosc życia warunkująca zdażenia podczas huraganu dla róży
    public static final int hurricaneLifeWorthForTulip = 60; //ilosc życia warunkująca zdażenia podczas huraganu dla tulipana
    public static final int hurricaneLifeWorthForIris = 50; //ilosc życia warunkująca zdażenia podczas huraganu dla irysa
    public static final int rainWeatherLifeAdd = -20;

}
